### ISSUE TITLE
Unclear case with api_account.perm_matches and None request

### ISSUE THREAD

**Issue by moul** [scaleway/python-scaleway#13]
Reading the following [line](https://github.com/scaleway/python-scaleway/blob/develop/scaleway/tests/apis/test_api_account.py#L74):
```python
        self.assertTrue(self.api.perm_matches(None, 'object:*'))
```

I would assume the opposite,
can you clarify this case and maybe update the docstring?

**Comment by moul** [comment]
Ok I think that I got it -> always returning true when there is no request permission is useful to check if there is at least one rule having the same service; right ?

**Comment by brmzkw** [comment]
I really need to give a look to our github more often, I'm sorry for the delay.

The first parameter of `api.perm_matches` is the permission you want to query against the second argument, which represents the actual token's permissions.

From my point of view, giving `None` as first argument is like asking whether a token has at least the "not permission" or not. Which IMO should always evaluate to True.

Feel free to reopen the ticket if it doesn't answer the question, or if you have a specific usecase not covered.
