### ISSUE TITLE
add user_data parameter in create server API

### ISSUE THREAD

**Issue by komuW** [scaleway/python-scaleway#14]
I think it would be great to have ability to send user_data(usually text that is interpreted as bash script) when creating a server via the API, https://github.com/scaleway/api.scaleway.com/blob/master/contents/server.md#create-a-new-server-post

This way, a scaleway customer can be able to specify things that they would like to run during the server creation.

This already exists in other cloud platforms, eg:

The ovh create server api has a parameter called userData that you can specify:: https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/instance#POST
The digitalocean API also takes a parameter called user_data, https://developers.digitalocean.com/documentation/v2/#create-a-new-droplet
This is very useful especially when you want to automate creation of servers that are different from each other but are based off the same image.

**Comment by brmzkw** [comment]
It is actually possible by using the compute API.

```
# Get user data keys
$> curl -H 'X-Auth-Token: <X-Auth-Token>' https://cp-par1.scaleway.com/servers/<server_id>/user_data
{"user_data": ["ssh-host-fingerprints"]}

# Create a new user data (PATCH api/servers/:id/user_data/:key
$> curl -H 'X-Auth-Token: <X-Auth-Token>' https://cp-par1.scaleway.com/servers/<server_id>/user_data/user_data_key -X PATCH -H 'Content-Type: text/plain' -d 'user data value'

# Get user data keys
$> curl -H 'X-Auth-Token: <X-Auth-Token>' https://cp-par1.scaleway.com/servers/<server_id>/user_data
{"user_data": ["ssh-host-fingerprints", "user_data_key"]}

# Get user data content
$> curl -H 'X-Auth-Token: <X-Auth-Token>' https://cp-par1.scaleway.com/servers/<server_id>/user_data/user_data_key
user data value

# Delete user data
$> curl -H 'X-Auth-Token: <X-Auth-Token>' https://cp-par1.scaleway.com/servers/<server_id>/user_data/user_data_key -X DELETE
```

I will ensure it is added on our [API documentation](https://developer.scaleway.com/).

**Comment by komuW** [comment]
@brmzkw awesome, thanks.

**Comment by brmzkw** [comment]
btw: 

https://github.com/scaleway/api.scaleway.com/commit/ee5e18af7712a6d7aba18d1a632d7660dbe24470

https://developer.scaleway.com/#user-data
