### ISSUE TITLE
404 Error on retrieving organizations

### ISSUE THREAD

**Issue by DavHau** [scaleway/python-scaleway#29]
The first example of the readme `api.query().organizations.get()` fails with error 404:
{"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", "type": "404"}

**Comment by smumu** [comment]
Hello,
Same here, I guess this is because the SDK uses old API URLs (like cp-par1.scaleway.com instead of api.scaleway.com/instance/v1/zones/fr-par-1).
Is it possible to update the SDK?

**Comment by brmzkw** [comment]
Can you provide a snippet?

It's working fine for me.

```py
from scaleway.apis import AccountAPI, ComputeAPI
import sys

token = sys.argv[1]

api = AccountAPI(auth_token=token)
data = api.query().organizations.get()
assert 'organizations' in data

cp_api = ComputeAPI(auth_token=token)
data = cp_api.query().servers.get()
assert 'servers' in data
```

**Comment by smumu** [comment]
For me it was a bug on my side, sorry.

Anyway, don't you think the SDK should be updated to use the new endpoint? The API documentations recommends to not use old enpoints.

**Comment by brmzkw** [comment]
I am no longer working at Scaleway, but I imagine it would indeed be better to use the new endpoints. On the other hand, I also imagine they won't break backward compatibility as some opensource projects will still use the old URLs (cloud-init, docker, ...).

**Comment by smumu** [comment]
If you don't work at Scaleway anymore, does anyone maintain this project?

**Comment by brmzkw** [comment]
cc @jerome-quere

**Comment by abarbare** [comment]
URL endpoints wille be updated there https://github.com/scaleway/python-scaleway/pull/32
